dotnet-foundation/wg-maintainers

- Meetings/2021-11-01-meeting-minutes.md
- Meetings/2021-11-10-meeting-minutes.md
- Meetings/Template.md
- Proposals/Template.md
- README.md
- Adds meeting notes for the first meeting
- Update the readme with committee members and the link to the monthly meeting
- Adds a proposals directory and template
- Updates the meeting notes template
> Meeting notes for first meeting

- Meetings/2021-11-10-meeting-minutes.md
- Meetings/Template.md
- README.md
Fixing the spelling of my name in the various files.
> Fix my name

- Meetings/Template.md
- README.md
Just to make my commitment public.
> Add Sean to group list in README

- README.md
Added me according to https://github.com/dotnet-foundation/wg-maintainers/issues/41
I've tried to keep alphabetical order. That's why I added there 👍
> Add a new member to README.md

- README.md
This PR includes updated readme documentation file.
Added @furkandeveloper to membership section.
> 📝 [DOC] Updated Readme.md - Furkan GUNGOR

- Meetings/2022-01-12-meeting-minutes.md
Apologize for being a bit late with the notes, thanks to @nicoleabuhakmeh for stepping up and assisting with the notes.
I'll merge this so we have it for tonight's meeting, but please feel free to send a PR if there are any errors that need correcting.
* closes #50
> Notes Maintainers' Meeting 2022-01-12

- Meetings/2022-02-16=meeting-minutes.md
- Meetings/Template.md
- README.md
> Adds meeting notes for Feb 2022

- Meetings/2021-11-10-meeting-minutes.md
- Meetings/2021-12-08-meeting-minutes.md
- Meetings/2022-02-16-meeting-minutes.md
- Meetings/Template.md
I previously tried sharing from Teams which wasn't allowed, downloading worked.
> Adds recordings for previous meetings

- Meetings/2022-03-09-meeting-minutes.md
- Meetings/Template.md
- README.md
- Adds meeting notes for 2022-03-09, resolves #59
- Adds new member Halil İbrahim Kalkan, resolves #60
- Resolves #56 
- Resolves #55
> 2022-03-09 Meeting Notes

- Meetings/Meeting.ics
- README.md
Updates the link to the Team's meeting and replaces the ICS meeting file with the new one.
> Update meeting link and ICS

- Meetings/Meeting.ics
> (#66) Fix "importability" of ICS

- Meetings/2022-05-11-meeting-minutes.md
- Meetings/Template.md
> Meeting notes for 11 May 2022

- Meetings/2022-06-08-meeting-minutes.md
> Add 2022-06-08 meeting notes

- Meetings/Meeting.ics
- README.md
to match with the current state of things.
> Switched the start time from 21 UTC/17 EST to 20 UTC

- Meetings/2022-09-14-meeting-minutes.md
Apolgies for not getting these out earlier.
> Notes from 14 Sept 2022 meeting

- Meetings/2022-12-14-meeting-minutes.md
- Meetings/Template.md
Meeting notes for today's meeting. Fixes #77
> Meeting notes for 2022-12-14

- Meetings/2023-03-08-meeting-minutes.md
> 2023-03-08 Meeting Notes

- .github/ISSUE_TEMPLATE/agenda.md
> Add issue template for Meeting Agendas

- Meetings/2023-01-11-meeting-minutes.md
> 2022-01-11 Meeting Notes

- Meetings/2023-04-12-meeting-minutes.md
> Initial meeting notes for 2023-04-12
